Dev/documentation
cclib/Cclib.jl pull request #12
Opened 2023-07-13 02:50 UTC by vcanogil

Updating docs. 

This should result in having a simple outline of the purpose of the library and an example of using it.

2023-07-14 22:30 UTC, shivupa requested changes
1 minor change

2023-07-14 22:30 UTC, shivupa commented on docs/make.jl
> -    authors="Felipe S. S. Schneider <schneider.felipe@posgrad.ufsc.br> and contributors",
`authors="cclib development team",`

2023-07-16 20:17 UTC, vcanogil commented on docs/make.jl
> -    authors="Felipe S. S. Schneider <schneider.felipe@posgrad.ufsc.br> and contributors",
Done

2023-07-16 22:40 UTC, berquist approved these changes
Looks good, but how do I build the docs from the command line?

2023-07-18 01:20 UTC, merged